### ISSUE TITLE
Cost perspective of fuels

### ISSUE THREAD

**Issue by camiloramirezgo** [Open-Source-Spatial-Clean-Cooking-Tool/OnStove#25]
This issue is to brainstorm ideas for the main cost equation of OnSSTOVE.

**Comment by babakkhavari** [comment]
Biomass, biogas, electricity, LPG
LCCMtotal = LCCMfuel + LCCMstove + LCCMinfrastructure + LCCMopportunity 

•	LCCMinfrastructure only for electricity?
•	For biomass we add opportunity cost: time savings (only in case they gather themselves), health, fuel saving, improved forest ecosystem, reduced carbon emissions. We could also add LCCMopportunity for all fuels if we consider time of cooking as opportunity cost. 
•	For all fuels but electricity LCCMinfra = 0
•	What is used as solid biomass for cooking in Nepal. WB say firewood, cattle dung and agro-waste
•	Jeuland and Soo, use a learning cost. This is the cost of learning a new technology and perhaps we can add it as measurement for “unwillingness to change technology”

Biomass:
•	If collected by household themselves LCCMfuel = 0 but LCCMopportunity higher due to time of collection
•	LCCMinfrastructure = 0
•	LCCMstove, distinguish between improved and traditional
•	LCCMstove capital cost, O&M costs, lifetime, discount rate, efficiency

**Comment by babakkhavari** [comment]
Suggest using the formula introduced by: https://www.cleancookingalliance.org/binary-data/RESOURCE/file/000/000/459-1.pdf 

Total net benefits = Benefits – Costs = (Morb + Mort + Timesav + Carb + Bio) – (Cap + Prog + O&M + Fuel + Learn)

**Comment by babakkhavari** [comment]
Cap = capital costs, can perhaps be taken from here: https://www.sciencedirect.com/science/article/pii/S0360544219323369#bib38 (table 1)

O&M = operation and maintenance cost, can perhaps be taken from here: https://www.sciencedirect.com/science/article/pii/S0360544219323369#bib38 (table 1)

Efficiency  can perhaps be taken from here: https://www.sciencedirect.com/science/article/pii/S0360544219323369#bib38 (table 1)

**Comment by babakkhavari** [comment]
**The benefit part of the equation**

**Comment by babakkhavari** [comment]
**### The cost part of the equation above**

**Comment by babakkhavari** [comment]
After internal CCA meeting:

LCCMtotal = LCCMfuel + LCCMstove + LCCMinfrastructure + LCCM<sub>penalty<sub>

penalty = mort, morb, time saved, carbon and forest.

**Comment by babakkhavari** [comment]
What we still need is:
- Burning rate per stove
- Minimum wage for Nepal
- Discount rate

**Comment by babakkhavari** [comment]
Writing about the OnSSTOVE method it seems impossible to do the equation without taking into account traditional biomass in the benefit part. We have to add trad. biomass in **Morb** and **Mort** otherwise the values are useless. Same thing with **Carb**

**Comment by camiloramirezgo** [comment]
> Writing about the OnSSTOVE method it seems impossible to do the equation without taking into account traditional biomass in the benefit part. We have to add trad. biomass in **Morb** and **Mort** otherwise the values are useless. Same thing with **Carb**

@babakkhavari Why are they useless? aren't the outputs of the equations given as a cost? so for example the **Carb** equation:

_Carb = ccarb * X * [Fuel<sub>0</sub> * ( γ<sub>0</sub> * µ<sub>0</sub> / Ɛ<sub>f0</sub>) - Fuel<sub>i</sub> * ( γ<sub>i</sub> * µ<sub>i</sub> / Ɛ<sub>fi</sub>)] / 10<sup>6</sup>_

Removing the _Fuel<sub>0</sub>_ parameter (traditional biomass) we get:

_Carb = ccarb * X * [Fuel<sub>i</sub> * ( γ<sub>i</sub> * µ<sub>i</sub> / Ɛ<sub>fi</sub>)] / 10<sup>6</sup>_

This equation is still in cost units, as the value that makes it be a cost is the _ccarb_ term which is given in USD/MT.

**Comment by babakkhavari** [comment]
The benefits have to be relative to something. 

Take Morb and Mort. They become larger as RR increases. In this case you will end up with a larger benefit for "worse" fuels. By putting in the biomass we fix this. 

Alternatively we do _Net Cost = Cost - Benefits_ and then chose the the stove with lowest net cost?

**Comment by camiloramirezgo** [comment]
> Alternatively we do _Net Cost = Cost - Benefits_ and then choose the the stove with lowest net cost?

I think something around this. But we cannot see them as benefits, because a benefit is always relative to something and that is what we want to avoid (having a baseline). So I think we can do instead of benefits, something like externality costs, which will be Health cost, Carbon emissions cost and opportunity cost.

**Comment by babakkhavari** [comment]
Ok
